
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - db
  db:
    image: mysql:8.0.43-debian
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lab2
      MYSQL_DATABASE: php_Tarasov
    volumes:
      - db_data:/var/lib/mysql
  php-fpm:
    build:
      context:  . 
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
    - "9000"
    environment:
    - DB_HOST=db
    - DB_NAME=php_Tarasov
    - DB_USER=root
    - DB_PASS=lab2
    - DB_PORT=3306
volumes:
  db_data: 